### ISSUE TITLE
results extract is not the same with the results show up in SWMM5

### ISSUE THREAD

**Issue by hadominh** [timcera/swmmtoolbox#10]
Hi Tim. 
I use your swmmtoolbox to extract my SWMM5 output. 
However i found that the extracted results from swmmtoolbox is not the samw with results showing in the program.
I want to extract the Node flooding (which is in the summary Results) during the time series of each nodes.

What i did with SWMM:
I run the model and create the time series by objects, i chose 1 node that supposed to be flooded 
With the swmmtoolbox i did it in jupyter notebook:
from swmmtoolbox import swmmtoolbox as sw
filename = 'D:\\***\\15.10.out'
g = sw.extract(filename,[['node','N31-17-1', '']])
g.to_excel(r'abc_2.xlsx')

Then i compare that timeseries made by SWMM with the time series which create by swmmtoolbox 
And it is not fit with each other. 

This is the result from the model (the starting time)
Table - Node N31-17-1
          	          	Depth           	Head            	Volume          	Lateral Inflow  	Total Inflow    	Flooding        
Days      	Hours     	(m)             	(m)             	(m3)            	(CMS)           	(CMS)           	(CMS)           
0         	00:01:00  	0.00            	5.77            	0.00            	0.00            	0.00            	0.00            

	node_N31-17-1_Depth_above_invert	node_N31-17-1_Hydraulic_head	node_N31-17-1_Volume_stored_ponded	node_N31-17-1_Lateral_inflow	node_N31-17-1_Total_inflow	node_N31-17-1_Flow_lost_flooding
2020-10-14 00:01:00	0.000103365	5.773803711	0	2.41268E-05	2.82158E-05	0

So, as we can se that only the Head is fit, but the Depth and the other are not. 
I come further than that, then even the head completely is not fit.

Table - Node N31-17-1
          	          	Depth           	Head            	Volume          	Lateral Inflow  	Total Inflow    	Flooding        
Days      	Hours     	(m)             	(m)             	(m3)            	(CMS)           	(CMS)           	(CMS)           
1         	18:37:00  	1.34            	7.12            	58.23           	0.00            	0.10            	0.04            

node_N31-17-1_Depth_above_invert	node_N31-17-1_Hydraulic_head	node_N31-17-1_Volume_stored_ponded	node_N31-17-1_Lateral_inflow	node_N31-17-1_Total_inflow	node_N31-17-1_Flow_lost_flooding
2020-10-15 18:37:00	0.391102254	6.164802551	0	8.8702E-05	0.006102621	0

i dont know if i run the code wrong? 
I use the CMS flow units in the model. 

Thank you !

**Comment by timcera** [comment]
I have seen this before and the swmmtoolbox output matched what was in the report file so I took that to mean the bug was in the SWMM interface.  Could you check in the report file for the same time-series and see which it matches?

Kind regards,
Tim

**Comment by hadominh** [comment]
Hi Tim,
Thank you for your respond. I have just check it. It were 2 issues:
1. as you said - the time series was not the same (one is elapsed time and ones is Date time). I re run the model this morning and check it again. It seem looked better than yesterday.
2.  SWMM5 interface report also round up the number into 2 decimals after the point. Therefore, sometime, it is not the really similar with the result extract by swmmtoolbox. I tried to round extracted result and it gave the same pattern comparing with SWMM5. 
Thank you! Issues are solved!
