### ISSUE TITLE
"extract" method should be updated

### ISSUE THREAD

**Issue by Nils-TalTech** [timcera/swmmtoolbox#7]
Hello,

> result = pd.concat(jtsd, axis=1, join_axes=[jtsd[0].index])

 seem to be not supported any more in Pandas ja yields an error "concat() got an unexpected keyword argument 'join_axes'"

If I substituted the row with:

> result =  pd.concat(jtsd, axis=1).reindex(jtsd[0].index)

this seems to work fine and no error is thrown! Please check and change the code if neccesary.

**Comment by timcera** [comment]
Fixed in 3963e6d2bf493034b2ef7b420b24df56c8679f37 and published in version 3.1.2.

Thanks!
